In [2]:
import numpy as np

Valid Sudoku

In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [4]:
# Check the given sudoku is valid or not

b = np.sum(s,axis=1)
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [5]:
for i in b:
    if i!=45:
        print("sudoku is not valid...")
        break
else:
    print("for rows it is valid")


for rows it is valid


In [6]:
c = np.sum(s,axis = 0)
c
for i in b:
    if i!=45:
        print("sudoku is not valid...")
        break
else:
    print("for cols it is valid")


for cols it is valid


In [10]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [ ]:
# inside s 3*3 matrix

s[0:3,0:3]    #first[0:3] is rows and 2nd ones are the cols

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [11]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [13]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [14]:
s[3:6,0:3]

array([[8, 5, 9],
       [4, 2, 6],
       [7, 1, 3]])

In [15]:
s[6:9,6:9]

array([[2, 8, 4],
       [6, 3, 5],
       [1, 7, 9]])

In [18]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n)
        print(n.sum())

[[5 3 4]
 [6 7 2]
 [1 9 8]]
45
[[6 7 8]
 [1 9 5]
 [3 4 2]]
45
[[9 1 2]
 [3 4 8]
 [5 6 7]]
45
[[8 5 9]
 [4 2 6]
 [7 1 3]]
45
[[7 6 1]
 [8 5 3]
 [9 2 4]]
45
[[4 2 3]
 [7 9 1]
 [8 5 6]]
45
[[9 6 1]
 [2 8 7]
 [3 4 5]]
45
[[5 3 7]
 [4 1 9]
 [2 8 6]]
45
[[2 8 4]
 [6 3 5]
 [1 7 9]]
45


# General question

In [55]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18,85,78],   #Student 1
    [19,92,88],    #Student 2
    [17,76,95],     #Student 3
    [18,65,70],     #Student 4
    [20,90,85]      #Student 5
])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [56]:
# Get the shape of the matrix
data.shape

(5, 3)

In [57]:
# find the average age of the matrix
np.mean(data[:,0])   # here inside the func 1st we pass the rows of the matrix and then the clos of the matrix

np.float64(18.4)

In [58]:
# Extract Maths marks of all the students
data[:,1]

array([85, 92, 76, 65, 90])

In [59]:
# Find he highest Science Marks
np.max(data[:,2])


np.int64(95)

In [60]:
# Get the details of the student who scored more than 90 in math...
data[data[:,1] >90]

array([[19, 92, 88]])

In [61]:
# Increase Maths marks of all students by 5
data[:,1]+5


array([90, 97, 81, 70, 95])

In [62]:
# Find how many students are younger than 19
len(data[data[:,0]<19])


3

In [63]:
# Calculate the average marks in each subject (col wise mean)
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [64]:
# Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >=80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [65]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [66]:
# Replace all Science marks < 75 with 0
data[:,2][data[:,2] <75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])