# Array Operations


Arithmatic operations


In [1]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])  # here the both array must have the equal length 
a2

array([ 6,  7,  8,  9, 10])

In [6]:
arr2 = a1+a2  
arr2
# a1-a2
# a1*a2
# a1/a2
# a1//a2
# a1**a2
# these are all the operations we can perfom in these two arrays

array([ 7,  9, 11, 13, 15])

Broadcasting :- Broadcasting is a technique that allows NumPy to perform operations on arrays of different shapes automatically.

In [9]:
l = [10,20,30,40]
arr = np.array(l)


In [10]:
# to add the 10 inn the list we have to do the loop b/w 1 to n to overcome it we can use the array and this will directly add the nums by 10
arr+10

array([20, 30, 40, 50])

In [11]:
m1 = np.arange(1,26).reshape(5,5)
m1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
m1+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and Shallow copy

In [14]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
slice = a[:5]
slice 
# here we can perform the operations as well in the slice
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# deep and shallow copy
| Feature       | Shallow Copy                    | Deep Copy                      |
| ------------- | ------------------------------- | ------------------------------ |
| Definition    | Copies only outer structure     | Copies everything recursively  |
| Memory        | Shares inner objects            | Creates completely new objects |
| Change Effect | Changes may reflect in original | No effect on original          |
| Speed         | Faster                          | Slower                         |
| Use Case      | When data is simple             | When data is nested            |


Matrix operations

In [19]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [21]:
A

array([[1, 2],
       [3, 4]])

In [22]:
B

array([[5, 6],
       [7, 8]])

In [25]:
B.T  # this for the matrix transpose

array([[5, 7],
       [6, 8]])

In [23]:
A @ B  # this is the way to do the matrix multiplication

array([[19, 22],
       [43, 50]])

In [24]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

# Advance Array Manipulation

Stacking Array

In [37]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [43]:
a

array([[1, 2],
       [3, 4]])

In [45]:
b

array([[5, 6],
       [7, 8]])

In [46]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [47]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [49]:
np.column_stack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Splitting Array

In [50]:
c =np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
np.hsplit(c, 2)  # Splits into 2 parts of 2 columns each

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [54]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]