In [2]:
import numpy as np

Basic Array Creation

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
a = [1,2,3,4,5,6,4.5,"mohit"]
a

[1, 2, 3, 4, 5, 6, 4.5, 'mohit']

In [ ]:
np.array(a)
# here all the values are converted into the floot and if there is mix datatypes then the given list converted to the array of string <U32>

array(['1', '2', '3', '4', '5', '6', '4.5', 'mohit'], dtype='<U32')

In [10]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generaion Function

In [13]:
arr1 = np.arange(1,10,2) # with this function we can generate the range like 1 to 9 of somthing like that
arr1

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros(6) #with this function we can gernerate the no of 0s we want 

In [16]:
arr = np.zeros((6,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr = np.ones((4,3)) #only generate the ones
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
arr2 = np.linspace(1,5,2)  #Give me N equal points between two numbers”
# start → beginning value
# stop → ending value
# num → total numbers you want
arr2

array([1., 5.])

Random Generation function

In [25]:
np.random.rand(10)

array([7.39391146e-01, 2.15295903e-01, 8.03824464e-04, 9.61945681e-01,
       4.75891731e-01, 1.38722007e-01, 6.35517225e-01, 9.66599419e-01,
       9.05409639e-01, 8.94980070e-01])

In [26]:
np.random.randn(10)

array([ 0.49487212, -2.13239359,  0.99159251, -0.0998923 ,  0.80082066,
       -1.81146577,  0.28503804, -1.39659711,  0.16600941,  0.54789431])

In [30]:
a = np.random.randint(10,20,10)
a

array([18, 16, 19, 13, 11, 12, 15, 17, 19, 13], dtype=int32)

## NumPy Random Functions Comparison

| Function | Description | Parameters | Range of Values | Distribution | Example |
|----------|------------|------------|----------------|--------------|---------|
| rand() | Generates random numbers | rand(d0, d1, ..., dn) → shape as separate arguments | [0, 1) | Uniform distribution | np.random.rand(2,3) |
| randn() | Generates random numbers | randn(d0, d1, ..., dn) → shape as separate arguments | (-∞, +∞) | Normal (Gaussian) distribution (mean=0, std=1) | np.random.randn(2,3) |
| randint() | Generates random integers | randint(low, high, size) → range + shape | [low, high) | Uniform (discrete) | np.random.randint(1, 10, (2,3)) |

Array Attributes  
These are properties that tell you structure and details of an array

## NumPy Array Attributes

| Attribute | Description | Example Output |
|----------|------------|---------------|
| arr.ndim | Number of dimensions | 2 |
| arr.shape | Shape (rows, columns) | (2, 3) |
| arr.size | Total number of elements | 6 |
| arr.dtype | Data type of elements | int32 / float64 |
| arr.itemsize | Size of each element (bytes) | 4 or 8 |
| arr.nbytes | Total memory used | 48 |
| arr.T | Transpose of array | Swaps rows & columns |

In [48]:
arr = np.array([[0,2,3,3],[4,5,6,0],[10,44,11,23]])
arr

array([[ 0,  2,  3,  3],
       [ 4,  5,  6,  0],
       [10, 44, 11, 23]])

In [32]:
arr.shape

(3, 4)

In [33]:
arr.size

12

In [34]:
arr.dtype

dtype('int64')

Array Methods
Array methods in NumPy are functions applied on arrays to perform operations like reshaping, aggregation, sorting, and type conversion.



## NumPy Array Methods

| Method | Description | Example |
|--------|------------|---------|
| arr.reshape() | Changes shape of array | arr.reshape(2,3) |
| arr.flatten() | Converts to 1D array (copy) | arr.flatten() |
| arr.ravel() | Converts to 1D (view, faster) | arr.ravel() |
| arr.transpose() / arr.T | Transpose rows ↔ columns | arr.T |
| arr.astype() | Change data type | arr.astype(float) |
| arr.copy() | Creates a copy of array | arr.copy() |
| arr.view() | Creates a view (linked data) | arr.view() |
| arr.sort() | Sorts array in-place | arr.sort() |
| arr.sum() | Sum of elements | arr.sum() |
| arr.mean() | Mean of elements | arr.mean() |
| arr.max() | Maximum value | arr.max() |
| arr.min() | Minimum value | arr.min() |
| arr.argmax() | Index of max value | arr.argmax() |
| arr.argmin() | Index of min value | arr.argmin() |

In [49]:
arr

array([[ 0,  2,  3,  3],
       [ 4,  5,  6,  0],
       [10, 44, 11, 23]])

In [50]:
arr.min()


np.int64(0)

In [40]:
arr.max()

np.int64(44)

In [41]:
arr.sum()

np.int64(112)

In [ ]:
np.sum(arr,axis=0)  #for rows axis will be 1 and for column axis is 0

array([15, 51, 20, 26])

In [44]:
arr.mean()

np.float64(9.333333333333334)

In [45]:
arr.std()

np.float64(12.043901176759777)

In [46]:
arr.argmax()

np.int64(9)

In [51]:
arr.argmin()

np.int64(0)

Reashaping and Resizing

In [55]:
arr3 = np.arange(1,16)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr3.reshape(3,5)  # 3 rows and 5 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## Difference Between Array Attributes and Array Methods

| Feature | Array Attributes | Array Methods |
|--------|-----------------|---------------|
| Definition | Properties that describe the array | Functions that perform operations on the array |
| Usage | Accessed without parentheses | Called using parentheses |
| Syntax | arr.shape | arr.reshape() |
| Purpose | Provide information about array | Modify or compute values |
| Example | arr.ndim, arr.dtype | arr.sum(), arr.sort() |
| Output | Returns metadata (info) | Returns processed data or modifies array |

Numpy Indexing and Slicing of vectors


In [57]:
narr = np.arange(11,21)
narr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
narr[0]   # here we can directly retrive the element by the index of the element same indexing as he list

np.int64(11)

In [59]:
narr[1:5]

array([12, 13, 14, 15])

In [60]:
# Assume example:
# narr = np.array([10, 20, 30, 40, 50, 60])

narr[:]      # Selects ALL elements (full copy/view of array)

narr[1:]     # Selects elements from index 1 to end
             # → [20, 30, 40, 50, 60]

narr[3::2]   # Starts from index 3, goes till end, step = 2
             # → Picks every 2nd element from index 3
             # → [40, 60]
narr[:3]     # first 3 elements → [10, 20, 30]
narr[::-1]   # reverse array → [60, 50, 40, 30, 20, 10]


array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

Numpy Indexing and Slicing of Matrix

In [62]:
arrn = np.arange(1,31).reshape(6,5)
arrn

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arrn[5] 

# array([[ 1,  2,  3,  4,  5],   this is the 0 index
#        [ 6,  7,  8,  9, 10],   1 index
#        [11, 12, 13, 14, 15],   2 index
#        [16, 17, 18, 19, 20],   3 index
#        [21, 22, 23, 24, 25],   4 index
#        [26, 27, 28, 29, 30]])  5 index
# Same for the col

array([26, 27, 28, 29, 30])

In [65]:
# For print any specific eleme in the metrix then
arrn[0,0]  # 1st eleme of the metrix


np.int64(1)

In [67]:
#  here we want to slicing the matrix form 2,3 and 7, 8
slice = arrn[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [74]:
# next slice these element form the matrix 19, 20 : 24, 25 : 29,30
slice = arrn[3: ,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [75]:
arrn[:,2]

array([ 3,  8, 13, 18, 23, 28])

Boolean Indexing

In [83]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [85]:
bool_index = arr%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [86]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# Next part is Array Operations